<a href="https://colab.research.google.com/github/dingin917/classify-handwritten-digits/blob/master/conv_filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Convolutional filter

![alt text](http://deeplearning.stanford.edu/wiki/images/6/6c/Convolution_schematic.gif)
> 
This code implements a function that computes the 2D Cross-Correlation (same as convolution but without flipping the kernel) between an image and a convolutional filter (we still call it convolutional for simplicity).
The function accepts the following parameters:
## Image
The 2D numpy array of size [image_height, image_width]
## Kernel
The 2D numpy array of size F we are convolving the image with
## Stride
This parameter determines how many pixels we slide the filter(kernel) when computing the next output pixel.
When the stride is 1 then we move the filter one pixel at a time. When the stride is 2 then the filter jumps 2 pixels at a time as we slide it around the input. This will produce smaller output volume spatially.

![alt text](http://cs231n.github.io/assets/cnn/stride.jpeg)

## Padding
This is a usual practice to pad the inputs with zeros around the border. This is done to make the output have the same spatial dimensions as the inputs.



# Now let's implement it
## Firstly, with stride=1 and no padding

In [1]:
import numpy as np  # we will use numpy arrays for this part of the assignment

def convolve(image, kernel):
    # This function computes the cross-correlation
    # between the image and the kernel
    # Args:
    #   image: a numpy array of size [image_height, image_width]
    #   kernel: a numpy array of size [kernel_height, kernel_width]
    # Returns:
    #   a numpy array of size [output_height, output_width].
    
    W1 = image.shape[1] # image_width
    H1 = image.shape[0] # image_height 
    F = kernel.shape[0] # kernel_heigh = kernel_width    
    assert F == kernel.shape[1] # make sure the filter is square
    W2 = (W1 - F) + 1 # with of the output, depends on the 
    H2 = (H1 - F) + 1 # height of the output
    
    output = np.zeros([H2, W2]) # output of the cross-correlation operation
        
    for y in range(output.shape[0]):     # loop over every row of the output
        for x in range(output.shape[1]): # loop over every pixel of the row           
            # element-wise multiplication of the kernel and the image            
            output[y,x]=(kernel*image[y:y+F,x:x+F]).sum()    
    return output.astype(int)
    
image = np.array([[1,2,3,4,3],[1,3,4,3,1],[0,1,5,1,0],[1,3,4,3,1],[2,4,3,2,2]]) # here's your input image
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
output = convolve(image,kernel)
print("Image:")
print(image)
print("\n Kernel:")
print(kernel)
print("\n Output:")
print(output)

Image:
[[1 2 3 4 3]
 [1 3 4 3 1]
 [0 1 5 1 0]
 [1 3 4 3 1]
 [2 4 3 2 2]]

 Kernel:
[[ 0 -1  0]
 [-1  5 -1]
 [ 0 -1  0]]

 Output:
[[ 7  6  5]
 [-6 15 -6]
 [ 5  6  7]]


## Now modify lines marked by "modify code here" to make it work for strides other than 1 and with zero-padding

In [13]:
import numpy as np

def convolve_better(image, kernel, stride=1, padding=False):
    # This function computes the cross-correlation
    # between the image and the kernel
    # Args:
    #   image: a numpy array of size [image_height, image_width].
    #   kernel: a numpy array of size [kernel_height, kernel_width].
    #   stride: integer
    #   padding: bool value indicating whether zero padding is used or not
    # Returns:
    #   a numpy array of size [output_height, output_width].
    
    W1 = image.shape[1] # image_width
    H1 = image.shape[0] # image_height
    S = stride # determines how many pixels we slide the filter
    F = kernel.shape[0] # kernel_heigh = kernel_width    
    assert F == kernel.shape[1] # make sure the filter is square
    # To correctly compute the dimensions of the output you need to account
    # for the amount of pixels added by padding (P)
    P = 1 if padding else 0 # number of pixels added with padding 
                            # around the image border
    ############################################################################    
    # You need to correctly compute the output image size given:
    # 1) Input image size (W1, H1)
    # 2) Image padding P
    # 3) Stride S
    # 4) Kernal size F 
    # modify code here:
    W2 = (W1 - F + 2*P)//S + 1 # width of the output 
    H2 = (H1 - F + 2*P)//S + 1 # height of the output
    ############################################################################
    
    output = np.zeros([H2, W2]) # output of the cross-correlation operation
    # Add zero padding to the input image      
    if padding:
        image_padded = np.zeros((image.shape[0] + 2*P, image.shape[1] + 2*P)).astype(int) 
        image_padded[P:-P, P:-P] = image
        print("Image padded:")
        print(image_padded)
    else: 
        image_padded = image
    
    for y in range(output.shape[0]):     # loop over every row of the output
        for x in range(output.shape[1]): # loop over every pixel of the row           
            # element-wise multiplication of the kernel and the image            
            ####################################################################
            # You need to correctly account for the stride other than 1
            # modify code here:
            output[y,x]=(kernel*image_padded[y*S:y*S+F,x*S:x*S+F]).sum()   
            ####################################################################
    return output.astype(int)
    
image = np.array([[1,2,3,4,3],[1,3,4,3,1],[0,1,5,1,0],[1,3,4,3,1],[2,4,3,2,2]]) 
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
output = convolve_better(image,kernel, stride=1, padding=True) # change parameters here
print("\n Image:")
print(image)
print("\n Kernel:")
print(kernel)
print("\n Output:")
print(output)

Image padded:
[[0 0 0 0 0 0 0]
 [0 1 2 3 4 3 0]
 [0 1 3 4 3 1 0]
 [0 0 1 5 1 0 0]
 [0 1 3 4 3 1 0]
 [0 2 4 3 2 2 0]
 [0 0 0 0 0 0 0]]

 Image:
[[1 2 3 4 3]
 [1 3 4 3 1]
 [0 1 5 1 0]
 [1 3 4 3 1]
 [2 4 3 2 2]]

 Kernel:
[[ 0 -1  0]
 [-1  5 -1]
 [ 0 -1  0]]

 Output:
[[ 2  3  5 11 10]
 [ 1  7  6  5 -1]
 [-3 -6 15 -6 -3]
 [ 0  5  6  7  0]
 [ 5 12  5  2  7]]
